__include__: [
  '../dataset/bdd_detection_kaggle.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: /kaggle/working/output/rtdetrv2_starnets4


RTDETR:
  backbone: StarNet

StarNet:
  name: 'starnet_s4'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [64, 128, 256]
  hidden_dim: 128
#  expansion: 0.5
  sfe_channel: 64


RTDETRTransformerv2:
  num_layers: 3
  feat_channels: [128, 128, 128]
  feat_strides: [8, 16, 32]
  hidden_dim: 128


epoches: 24

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader: 
  dataset:
    transforms:
      policy:
        epoch: 20
  collate_fn:
    scales: ~